name: Build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'npm'
            - run: npm ci
            - name: Assets
              uses: actions/cache@v4
              with:
                path: data
                key: data-${{github.ref}}-${{hashFiles('data/**/*')}}
                restore-keys: |
                              data-${{github.ref}}
                              data-main
            - run: ./makeBundle.sh
            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                name: tappdex
                path: |
                      dist
    create-release:
        runs-on: ubuntu-latest
        needs: build
        if: github.ref_type == 'tag'
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: tappdex
            - run: ls -l
            # - name: Create release
            #     uses: softprops/action-gh-release@v2
            #     with:
            #     files: tappdex.zip
    
                      